export const NEW_STORY_REQUEST = "NEW_STORY_REQUEST";
export const NEW_STORY_SUCCESS = "NEW_STORY_SUCCESS";
export const NEW_STORY_RESET = "NEW_STORY_RESET";
export const NEW_STORY_FAIL = "NEW_STORY_FAIL";

export const ALL_STORY_REQUEST = "ALL_STORY_REQUEST";
export const ALL_STORY_SUCCESS = "ALL_STORY_SUCCESS";
export const ALL_STORY_FAIL = "ALL_STORY_FAIL";

export const STORY_DETAILS_REQUEST = "STORY_DETAILS_REQUEST";
export const STORY_DETAILS_SUCCESS = "STORY_DETAILS_SUCCESS";
export const STORY_DETAILS_FAIL = "STORY_DETAILS_FAIL";

export const DELETE_STORY_REQUEST = "DELETE_STORY_REQUEST";
export const DELETE_STORY_SUCCESS = "DELETE_STORY_SUCCESS";
export const DELETE_STORY_RESET = "DELETE_STORY_RESET";
export const DELETE_STORY_FAIL = "DELETE_STORY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
