export const NEW_STORY_REQUEST = "NEW_STORY_REQUEST";
export const NEW_STORY_SUCCESS = "NEW_STORY_SUCCESS";
export const NEW_STORY_RESET = "NEW_STORY_RESET";
export const NEW_STORY_FAIL = "NEW_STORY_FAIL";

export const ALL_STORY_REQUEST = "ALL_STORY_REQUEST";
export const ALL_STORY_SUCCESS = "ALL_STORY_SUCCESS";
export const ALL_STORY_FAIL = "ALL_STORY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
